import { MD3Type } from 'react-native-paper/lib/typescript/types';

const font: Record<string, MD3Type> = {
  // place holder definition for web
  displayH1: {
    fontFamily: 'OpenSans-SemiBold',
    fontSize: 46,
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 68,
  },
  displayH2: {
    fontFamily: 'OpenSans-SemiBold',
    fontSize: 38,
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 56,
  },
  displayH3: {
    fontFamily: 'OpenSans-SemiBold',
    fontSize: 28,
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 42,
  },
  headlineH4: {
    fontFamily: 'OpenSans-SemiBold',
    fontSize: 24,
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 38,
  },
  headlineH5: {
    fontFamily: 'OpenSans-SemiBold',
    fontSize: 22,
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 32,
  },
  headlineH6: {
    fontFamily: 'OpenSans-SemiBold',
    fontSize: 20,
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 30,
  },
  bodySubtitle1: {
    fontFamily: 'OpenSans-SemiBold',
    fontSize: 15,
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 22,
  },
  bodySubtitle2: {
    fontFamily: 'OpenSans-SemiBold',
    fontSize: 13,
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 20,
  },
  bodyBody1: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 15,
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 22,
  },
  bodyBody2: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 13,
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 20,
  },
  bodyCaption: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 13,
    fontWeight: '400',
    letterSpacing: 0.4,
    lineHeight: 18,
  },
  bodyOverline: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 13,
    fontWeight: '400',
    letterSpacing: 0.8,
    lineHeight: 14,
  },
  // main
  buttonLarge: {
    fontFamily: 'OpenSans-SemiBold',
    fontSize: 17,
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 26,
  },
  buttonMedium: {
    fontFamily: 'OpenSans-SemiBold',
    fontSize: 15,
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 22,
  },
  buttonSmall: {
    fontFamily: 'OpenSans-SemiBold',
    fontSize: 13,
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 18,
  },
  fabButtonLarge: {
    fontFamily: 'OpenSans-SemiBold',
    fontSize: 17,
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 24,
  },
  fabButtonSmall: {
    fontFamily: 'OpenSans-SemiBold',
    fontSize: 13,
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 24,
  },
  inputLabel: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 13,
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 15,
  },
  helperText: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 13,
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 13,
  },
  inputTextLarge: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 17,
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 24,
  },
  inputTextMedium: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 15,
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 24,
  },
  inputTextSmall: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 13,
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 22,
  },
  avatarInititals: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 15,
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 18,
  },
  chip: {
    fontFamily: 'OpenSans-SemiBold',
    fontSize: 13,
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 20,
  },
  tooltip: {
    fontFamily: 'OpenSans-SemiBold',
    fontSize: 13,
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 20,
  },
  alertText: {
    fontFamily: 'OpenSans-SemiBold',
    fontSize: 15,
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 24,
  },
  tableHeader: {
    fontFamily: 'OpenSans-Bold',
    fontSize: 13,
    fontWeight: '400',
    letterSpacing: 0.2,
    lineHeight: 24,
  },
  badgeLabel: {
    fontFamily: 'OpenSans-SemiBold',
    fontSize: 13,
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 14,
  },
  toast: {
    fontFamily: 'OpenSans-SemiBold',
    fontSize: 15,
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 22,
  },
  pointment: {
    fontFamily: 'OpenSans-SemiBold',
    fontSize: 12,
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 16,
  },
  pointmentSmall: {
    fontFamily: 'OpenSans-Bold',
    fontSize: 9,
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 16,
  },
  onSurface: {
    fontFamily: 'OpenSans-SemiBold',
    fontSize: 12,
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 16,
  },
  onSurfaceSmall: {
    fontFamily: 'OpenSans-SemiBold',
    fontSize: 9,
    fontWeight: '400',
    letterSpacing: 0,
    lineHeight: 16,
  },
};

export default font;
